// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJXgbbktMQEkXS8yhC2zHJJP5pBfQKzTo',
    appId: '1:174725538502:web:08cc98db6ccb1a92ba2dc7',
    messagingSenderId: '174725538502',
    projectId: 'fish-and-meat-5412e',
    authDomain: 'fish-and-meat-5412e.firebaseapp.com',
    storageBucket: 'fish-and-meat-5412e.firebasestorage.app',
    measurementId: 'G-RZJSKCB1ZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIzrGoqiWJzdYwmidyczIRv4SJlGV8I8g',
    appId: '1:174725538502:android:9e2ddfd2aa4577e2ba2dc7',
    messagingSenderId: '174725538502',
    projectId: 'fish-and-meat-5412e',
    storageBucket: 'fish-and-meat-5412e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Yew4-axWLQkdkVYx7RlLO8x_pQq68XY',
    appId: '1:174725538502:ios:949cd0c36d056051ba2dc7',
    messagingSenderId: '174725538502',
    projectId: 'fish-and-meat-5412e',
    storageBucket: 'fish-and-meat-5412e.firebasestorage.app',
    iosBundleId: 'com.example.fishMeat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-Yew4-axWLQkdkVYx7RlLO8x_pQq68XY',
    appId: '1:174725538502:ios:949cd0c36d056051ba2dc7',
    messagingSenderId: '174725538502',
    projectId: 'fish-and-meat-5412e',
    storageBucket: 'fish-and-meat-5412e.firebasestorage.app',
    iosBundleId: 'com.example.fishMeat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJXgbbktMQEkXS8yhC2zHJJP5pBfQKzTo',
    appId: '1:174725538502:web:728582a3e81f0709ba2dc7',
    messagingSenderId: '174725538502',
    projectId: 'fish-and-meat-5412e',
    authDomain: 'fish-and-meat-5412e.firebaseapp.com',
    storageBucket: 'fish-and-meat-5412e.firebasestorage.app',
    measurementId: 'G-8LS44VY6QB',
  );
}
